972-topology-card-context-menu-position-fixed-wont-hidden-less-height-accommodate
flanksource/flanksource-ui pull request #1034
Opened 2023-03-28 19:34 UTC by mainawycliffe

Prevent overflow showing when there isn't enough height

Closes #972 and Closes #942

2023-03-29 11:30 UTC, Prashanth-Nelli requested changes

2023-03-29 11:32 UTC, mainawycliffe commented on src/components/TopologyCard/TopologyDropdownMenu.tsx
> +      return `right-[${right}] top-[${top}]`;
Nice catch; for some reason, it's still working wondering why now?

2023-03-29 11:39 UTC, Prashanth-Nelli commented on src/components/TopologyCard/TopologyDropdownMenu.tsx
> +      return `right-[${right}] top-[${top}]`;
we can remove this block if it is not required.

2023-04-03 18:40 UTC, mainawycliffe commented on src/components/TopologyCard/TopologyDropdownMenu.tsx
> +      return `right-[${right}] top-[${top}]`;
This is fixed now

2023-04-12 05:36 UTC, Prashanth-Nelli approved these changes
LGTM

2023-04-12 06:07 UTC, merged