Feat/react table prototyping
flanksource/flanksource-ui pull request #28
Opened 2021-09-15 10:05 UTC by johnflank

Changed old table to React Table, synced Table sort/group/filter parameters state to the URL. Improved sorting behavior for grouped items on Table.

2021-09-16 13:14 UTC, flanksaul requested changes

2021-09-16 13:14 UTC, flanksaul commented on src/components/Canary/table.js
> +  const { watch, setValue } = useForm({
This still to be handled?

2021-09-16 20:05 UTC, moshloop commented
@johnflank The default sorting should be by check ascending - it can be turned off - you must sort by something.
Sorting should also be case insensitive.

2021-09-17 11:00 UTC, flanksaul requested changes

2021-09-17 11:51 UTC, flanksaul requested changes

2021-09-17 11:51 UTC, flanksaul commented on src/components/Canary/table.js
> +      setSortBy([{ id: columnsKeyed.name.accessor, desc: false }]);
Default values need to be built in every render, so you need to initialise with defaults and then overwrite if they are present.

2021-09-21 07:37 UTC, closed without merging